### ISSUE TITLE
The server fails to run

### ISSUE THREAD

**Issue by shikata-ga-nai** [Zach-Rose-Bose/SoundTouch_Alexa_RemoteServer#1]
Hey,
I've just set up fresh instance of ubuntu 14.04 x64 on ec2, cloned the repo, installed nodejs, npm,
run `sudo npm install`
and then
`sudo nodejs .`

and an error with this stacktrace happens

```
$ sudo nodejs .
Web server listening at: http://0.0.0.0:80
Browse your REST API at http://0.0.0.0:80/explorer
Connection fails: MongoError: failed to connect to server [127.0.0.1:27017] on first connect
It will be retried for the next request.

/home/ubuntu/AlexaSoundTouch_RemoteServer/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongo_client.js:225
          throw err
                ^
MongoError: failed to connect to server [127.0.0.1:27017] on first connect
    at null.<anonymous> (/home/ubuntu/AlexaSoundTouch_RemoteServer/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at EventEmitter.emit (events.js:95:17)
    at null.<anonymous> (/home/ubuntu/AlexaSoundTouch_RemoteServer/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at g (events.js:180:16)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/ubuntu/AlexaSoundTouch_RemoteServer/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:180:16)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:459:13)
```

**Comment by zwrose** [comment]
This looks like it's an issue with loopback: strongloop/loopback-connector-mongodb#268

What version of loopback and the loopback mongodb connector are you using? I didn't see this error on loopback 2.27.0 and v1.13.3 of the connector.

**Comment by shikata-ga-nai** [comment]
@zwrose there was some issue with mongo, it didn't start properly, I reinstalled it and it works now. Thank you.
