### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by MrBobC** [Zach-Rose-Bose/SoundTouch_Alexa_RemoteServer#2]
Hi!  I'm very excited by this application you've developed, but I"m struggling.  I did the 64-bit EC2 instance of Ubuntu 14.04 on AWS, installed git-core, libnss-mdns, npm, mongo, libavahi-compat-libdnssd-dev, build-essential, and node v7.  I copied the distro, installed it, and I ran sudo node . and got the following (which I believe means it is working):
Web server listening at: http://0.0.0.0:80
Browse your REST API at http://0.0.0.0:80/explorer

For the lambda function I coped in the raw code from github, put in the ip address of my EC2 instance as well as the (s), inserted the information required on line 27 from my skill, and tested the lambda with the following code from saying "Alexa ask bose to pause":
{
  "session": {
    "sessionId": "SessionId.5de8ba83-7c32-430c-8f96-xxxxxxxxxxxx",
    "application": {
      "applicationId": "amzn1.ask.skill.4b783e3f-d79f-450b-99da-xxxxxxxxxxxx"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AG2ZR7IPAHI5NA2NBAAERB5QCI3SXSTAWH5HXHZPIJLZMRCORXWAEDUFDP2UW47FDKTPQXY2VQPQMB3DP2WWVOGQTCQFCV5EHZFVSDSWBXZRLRRDX7THICTXZ6VMWDXXUFH224H4OAJRNQCVBA7CA3DUMVVEIQLUZBGFYEZ4ZUNAHLWSVQVW7KVWIUW3XCWTO6Txxxxxxxxxxxx"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.ffa607e7-08b0-46a2-8fb0-xxxxxxxxxx",
    "locale": "en-US",
    "timestamp": "2016-12-11T02:22:49Z",
    "intent": {
      "name": "PauseIntent",
      "slots": {
        "Speaker": {
          "name": "Speaker"
        }
      }
    }
  },
  "version": "1.0"
}

For which the lambda response is:
START RequestId: dfc5d248-bf49-11e6-8ec8-xxxxxxxxxxxx Version: $LATEST
2016-12-11T02:31:08.942Z	dfc5d248-bf49-11e6-8ec8-xxxxxxxxxxxx	event.session.application.applicationId=amzn1.ask.skill.4b783e3f-d79f-450b-99da-xxxxxxxxxxxx
2016-12-11T02:31:08.942Z	dfc5d248-bf49-11e6-8ec8-xxxxxxxxxxxx	onSessionStarted requestId=EdwRequestId.f4a80a37-230b-4706-be10-38e210b26e1a, sessionId=SessionId.894c75bd-a22a-4872-9b4d-xxxxxxxxxxxx
2016-12-11T02:31:08.942Z	dfc5d248-bf49-11e6-8ec8-xxxxxxxxxxxx 	onIntent requestId=EdwRequestId.f4a80a37-230b-4706-be10-38e210b26e1a, sessionId=SessionId.894c75bd-a22a-4872-9b4d-xxxxxxxxxxxx
2016-12-11T02:31:08.942Z	dfc5d248-bf49-11e6-8ec8-xxxxxxxxxxxx 	Intents received:  { Speaker: { name: 'Speaker' } }
2016-12-11T02:31:08.945Z	dfc5d248-bf49-11e6-8ec8-xxxxxxxxxxxxx	Got error: connect ECONNREFUSED 127.0.0.1:80
END RequestId: dfc5d248-bf49-11e6-8ec8-773e10fe9460
REPORT RequestId: dfc5d248-bf49-11e6-8ec8-773e10fe9460	Duration: 4.58 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 17 MB	

Any help on the refused connection?  Thanks a bunch!

**Comment by Zach-Rose-Bose** [comment]
Might be tricky to debug without being in front of your code, but let's see if I can help!

So it looks like you successfully made it into the PauseIntent with a Speaker slot, but you never get to the "console.log('[ OK ] Speaker sent. Playing if valid and paused.');" line, so the issue is probably somewhere in getBoseHomeState(). You have the "Got error:" message in the log -- this only hits on either line 1001 or 1012 (using the line numbers in the original github repo), but if it was the 1001 line we'd also see "Home does not yet exist..."

So, it looks like the error is happening on the HTTP GET request to your EC2. This makes sense with the ECONNREFUSED error. This part is weird though: 127.0.0.1:80 -- that implies maybe that it's trying to call itself rather than the EC2 server? 

Can you put the following line in the skill: console.log(bridgeBasePath + '/api/homes/' + alexaID); at line 966 (right under `function getBoseHomeState(callback, alexaID, boseCallback) {`) and run it again and share the logs? If you don't mind, can you leave part of the IP address in (the first and last octet, maybe) when you post? I recognize that you won't want to post the whole thing.

Let me know what you see, or if you have questions!

**Comment by MrBobC** [comment]
Thanks for getting back to me, glad to see you keep an eye on this.  Here's the output, which I think means the code you asked me to insert worked because of that extra line that makes no sense to me.  :)

START RequestId: 72a90ed8-c0e3-11e6-8678-xxxxxxxxxxxx Version: $LATEST
2016-12-13T03:22:59.771Z	72a90ed8-c0e3-11e6-8678-xxxxxxxxxxxx	event.session.application.applicationId=amzn1.ask.skill.4b783e3f-d79f-450b-99da-xxxxxxxxxxxx
2016-12-13T03:22:59.773Z	72a90ed8-c0e3-11e6-8678-xxxxxxxxxxxx	onSessionStarted requestId=EdwRequestId.f4a80a37-230b-4706-be10-38e210b26e1a, sessionId=SessionId.894c75bd-a22a-4872-9b4d-xxxxxxxxxxxx
2016-12-13T03:22:59.773Z	72a90ed8-c0e3-11e6-8678-xxxxxxxxxxxx	onIntent requestId=EdwRequestId.f4a80a37-230b-4706-be10-38e210b26e1a, sessionId=SessionId.894c75bd-a22a-4872-9b4d-xxxxxxxxxxxx
2016-12-13T03:22:59.773Z	72a90ed8-c0e3-11e6-8678-xxxxxxxxxxxx	Intents received:  { Speaker: { name: 'Speaker' } }
2016-12-13T03:22:59.953Z	72a90ed8-c0e3-11e6-8678-xxxxxxxxxxxx	http(s)://54.xxx.xx.120/api/homes/amzn1.ask.account.AG2ZR7IPAHI5NA2NBAAERB5QCI3SXSTAWH5HXHZPIJLZMRCORXWAEDUFDP2UW47FDKTPQXY2VQPQMB3DP2WWVOGQTCQFCV5EHZFVSDSWBXZRLRRDX7THICTXZ6VMWDXXUFH224H4OAJRNQCVBA7CA3DUMVVEIQLUZBGFYEZ4ZUNAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2016-12-13T03:23:00.113Z	72a90ed8-c0e3-11e6-8678-xxxxxxxxxxxx	Got error: connect ECONNREFUSED 127.0.0.1:80
END RequestId: 72a90ed8-c0e3-11e6-8678-xxxxxxxxxxxx

**Comment by Zach-Rose-Bose** [comment]
Great! I think I see the issue: the documentation was slightly misleading -- when I specified "http(s)://", it was intended to mean "http://" OR "https://". I've updated this to be clearer!

In your bridgeBasePath variable (should be ~line 14), please remove the "(s)", and give it another try!

**Comment by MrBobC** [comment]
Okay the connection error is gone.  When I test for "Alexa ask bose to pause" I get:

{
  "errorMessage": "2016-12-13T13:49:22.088Z f1cdf81b-c13a-11e6-8ec8-xxxxxxxxxxxxTask timed out after 3.00 seconds"
}

START RequestId: f1cdf81b-c13a-11e6-8ec8-xxxxxxxxxxxx Version: $LATEST
2016-12-13T13:49:19.251Z	f1cdf81b-c13a-11e6-8ec8-xxxxxxxxxxxx	event.session.application.applicationId=amzn1.ask.skill.4b783e3f-d79f-450b-99da-xxxxxxxxxxxx
2016-12-13T13:49:19.251Z	f1cdf81b-c13a-11e6-8ec8-xxxxxxxxxxxx	onSessionStarted requestId=EdwRequestId.f4a80a37-230b-4706-be10-xxxxxxxxxxxx, sessionId=SessionId.894c75bd-a22a-4872-9b4d-xxxxxxxxxxxx
2016-12-13T13:49:19.252Z	f1cdf81b-c13a-11e6-8ec8-xxxxxxxxxxxx	onIntent requestId=EdwRequestId.f4a80a37-230b-4706-be10-xxxxxxxxxxxx, sessionId=SessionId.894c75bd-a22a-4872-9b4d-xxxxxxxxxxxx
2016-12-13T13:49:19.252Z	f1cdf81b-c13a-11e6-8ec8-xxxxxxxxxxxx	Intents received:  { Speaker: { name: 'Speaker' } }
2016-12-13T13:49:19.432Z	f1cdf81b-c13a-11e6-8ec8-xxxxxxxxxxxx	http://54.xxx.xx.120/api/homes/amzn1.ask.account.AG2ZR7IPAHI5NA2NBAAERB5QCI3SXSTAWH5HXHZPIJLZMRCORXWAEDUFDP2UW47FDKTPQXY2VQPQMB3DP2WWVOGQTCQFCV5EHZFVSDSWBXZRLRRDX7THICTXZ6VMWDXXUFH224H4OAJRNQCVBA7CA3DUMVVEIQLUZBGFYEZ4ZUNAHLWSVxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
END RequestId: f1cdf81b-c13a-11e6-8ec8-xxxxxxxxxxxx
REPORT RequestId: f1cdf81b-c13a-11e6-8ec8-xxxxxxxxxxxx	Duration: 3001.40 ms	Billed Duration: 3000 ms 	Memory Size: 128 MB	Max Memory Used: 7 MB	
2016-12-13T13:49:22.088Z f1cdf81b-c13a-11e6-8ec8-xxxxxxxxxxxx Task timed out after 3.00 seconds

My bridgebasepath is 54.xxx.xx.120, and my bridgeID is amzn1.ask.skill.4b783e3f-d79f-450b-99da-xxxxxxxxxxxx.  When I run that scenario (Alexa ask bose to pause) from the Amazon Skill test, I get: The remote endpoint could not be called, or the response it returned was invalid.

And based on the documentation I'm supposed to get a response saying that the corresponding home was created or doesn't have and speakers associated with it. That response will also contain an AlexaID - use this to configure your AlexaSoundTouch_LocalServer instance (the bridgeID var in server.js of the Local Server should be set as this AlexaID).

**Comment by Zach-Rose-Bose** [comment]
OK, on to the next one :). in a browser, can you go to http://54.xxx.xx.120/api/homes (using your real IP address) and let me know what you see?

**Comment by MrBobC** [comment]
I know the server is running, but it times out:

This site can’t be reached

54.xxx.xx.120 took too long to respond.

**Comment by Zach-Rose-Bose** [comment]
Interesting. Can you share the console output from the server when you make that browser request?

**Comment by MrBobC** [comment]
It does nothing.  It just says:

Web server listening at http://0.0.0.0:80
Browse your REST API at http://0.0.0.0:80/explorer

And in Chrome it just says "This site can't be reached
54.xxx.xx.120 took too long to respond.

It shouldn't matter I don't think but I'm using the public ip address displayed in AWS to point things at.

**Comment by Zach-Rose-Bose** [comment]
OK, thanks. The fact that it says "Web server listening at http://0.0.0.0:80" means that the remote server code is likely functioning as intended.

The challenge here is likely an AWS/EC2 configuration issue -- something that might not be easy for me to help troubleshoot. 

One area you should check is that you have HTTP port 80 allowed in your inbound security configuration. See this screenshot for what this would look like:

![aws security screenshot](https://cloud.githubusercontent.com/assets/22259579/21182856/2de4c1ea-c1d3-11e6-86e4-a153f906c621.PNG)

**Comment by MrBobC** [comment]
Okay, so that fixed that part.  After enabling that I did get:
loopback deprecated loopback#context middleware is deprecated. See https://docs.strongloop.com/display/APIC/Using%20current%20context for more details. node_modules/loopback/server/middleware/rest.js:60:32

on the remote server.  I did also create the home, and I am now told this home based on Alexa ID ... does not appear to have any speakers on the network. Please be sure the local server is running and reporting to the correct home instance in the remote server.  My local server is running and I think it is connected to the remote server, since if I stop the remote server the local one immediately gets refusal errors.

**Comment by Zach-Rose-Bose** [comment]
OK great. I'm not too worried about the deprecation warning at this point.

Can you confirm that you've set the bridgeID (~line 22) in the Local Server server.js file to exactly match the AlexaID string that the home is based on?

You should be able to go to http://54.xxx.xx.120/api/homes, see that string in the browser, copy it and paste it right in if it hasn't already been set.

**Comment by MrBobC** [comment]
For the ID I re-put the string in there, it starts with amzn1.ask.account.xxxxxx.... and it still says it doesn't appear to have any speakers on the network.  I see no activity in the console windows of either the remote or local server when I make the request.  Are there any restrictions with speaker names, like spaces or anything the list_of_speakers part of the skill?  I'm glad we're getting closer.  :)

**Comment by Zach-Rose-Bose** [comment]
OK - can you try uncommenting line 255:

![image](https://cloud.githubusercontent.com/assets/22259579/21197654/37d5859a-c20a-11e6-9b7a-b5ee457c076c.png)

Then try things again and let me know what you see in the console for the local server?

**Comment by MrBobC** [comment]
Okay, I've uncommented that line in server.js on the local server and retried "Alexa ask bose to pause" and received no feedback on either console (remote or local) and I still get

{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "This home, based on AlexaID: amzn1.ask.account.AG2ZR7IPAHI5NA2NBAAERB5QCI3SXSTAWH5HXHZPIJLZMRCORXWAEDUFDP2UW47FDKTPQXY2VQPQMB3DP2WWVOGQTCQFCV5EHZFVSDSWBXZRLRRDX7THICTXZ6VMWDXXUFH224H4OAJRNQCVBA7CA3DUMVVEIQLUZBGFYEZ4ZUNAHLWSVQVW7KVWIUW3XCWTO6TJGC6TAQDQ4XA, does not appear to have any speakers on the network. Please be sure the local server is running and reporting to the correct home instance in the remote server."
    },
    "card": {
      "content": "This home, based on AlexaID: amzn1.ask.account.xxxxx does not appear to have any speakers on the network. Please be sure the local server is running and reporting to the correct home instance in the remote server.",
      "title": "No Home State",
      "type": "Simple"
    },
    "reprompt": {
      "outputSpeech": {

My local server (run on virtualbox) says:
HTTP REST server listening on port 5006

**Comment by Zach-Rose-Bose** [comment]
That's really strange that all the local server says is the HTTP REST Server line.

Let's add some more logging to try and figure this out. On the local server, can you add a line between the existing line 155 `if(counter == 5) {` and line 156 `updateHomeState();`? The new line should be:

`console.log("Entering updateHomeState, counter = " + counter);`

**Comment by MrBobC** [comment]
Okay, so when I started the local server node the first line was "Entering updateHomeState, counter = 5" and then that line just repeats itself every few seconds.  Testing the "Alexa ask bose to pause" only results in the same as before about not having any speakers on the network.

**Comment by zwrose** [comment]
ok great -- thanks! you can comment that line out.

Now can you add this on line 199 (right before `// go get the list of speakers from the server`):

`console.log("blank homeState:", homeState);`

What I'm trying to detect with these console.logs is where the local server is going "silent" -- there hsould be more logging activity happening, so something is breaking somewhere, and we can find it by logging step by step.

Also, can you confirm line 14 still reads exactly:

`var stServerBasePath = 'http://127.0.0.1:5006';`

**Comment by MrBobC** [comment]
Okay, so line 14 reads exactly as you stated.  I added the log and get this regular output on the local server:

blank homeState: { speakers: {}, zonesPlaying: [] }

**Comment by zwrose** [comment]
OK, thanks! You can comment out that last console log. Now please add the following into line 204, right after `res.on('end', function() {` and right before `JSON.parse(listBody).forEach(function(element, index, array) {`

`console.log("listBody:", listBody);`

**Comment by MrBobC** [comment]
Now my repeating thing is:

listBody: []

And that's it.

**Comment by Zach-Rose-Bose** [comment]
Ok, that's helpful. It shows that the device discovery part of the code isn't finding any devices. I didn't write that code, so there's only so much I'll be able to help with here, but let's see what we can do.

First things first, can you confirm that the virtual machine you're running the local server on is on the same local network as your Soundtouch system?

You should be able to check this by first going into the Soundtouch app, going into about>your device and getting the IP address of the device. Then, from the virtual box command line, try and ping the Soundtouch device.

Let me know what result you get from the ping test.

**Comment by MrBobC** [comment]
Yes, I can ping all three of my SoundTouch devices.  I have two SoundTouch 20 Rev. II, and a Wave Music System Rev. III.

**Comment by Zach-Rose-Bose** [comment]
ok. hmm. That looks like it points to an issue with the discovery code not being able to find the speakers on the network. I inherited this functionality entirely from https://github.com/CONNCTED/SoundTouch-NodeJS - and I'm not familiar with how that works enough at this point to be able to troubleshoot it quickly. I might be able to dig into it at some point, but with the holidays upon us that likely won't be soon, unfortunately.

**Comment by MrBobC** [comment]
Okay, well at least we figured all this other stuff out.  I wonder why the discovery doesn't work for me but it seems to not have caused issues with anyone else (at least that had commented).  I guess I'll just have to wait for Bose to issue their skill in 2017.  Thanks for the help!

**Comment by MrJoker84** [comment]
I keep seeing MongoDB errors when I try starting remote server ... I'm seeing the following.  Any thoughts?

~/AlexaSoundTouch_RemoteServer$ sudo node .
Web server listening at: http://0.0.0.0:80
Browse your REST API at http://0.0.0.0:80/explorer
Connection fails: MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
It will be retried for the next request.

/home/ubuntu/AlexaSoundTouch_RemoteServer/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongo_client.js:417
          throw err
          ^
MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at null.<anonymous> (/home/ubuntu/AlexaSoundTouch_RemoteServer/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:329:35)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/home/ubuntu/AlexaSoundTouch_RemoteServer/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/home/ubuntu/AlexaSoundTouch_RemoteServer/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1272:8)
    at nextTickCallbackWith2Args (node.js:511:9)
    at process._tickDomainCallback (node.js:466:17)

**Comment by Zach-Rose-Bose** [comment]
Hi @MrJoker84 -- my firsthand knowledge of mongo is pretty limited, so I'm not immediately sure what the problem is here. This SO post seems to be a similar issue though: https://stackoverflow.com/questions/37576822/mongodb-mongoerror-connect-econnrefused -- maybe that can help?

**Comment by MrJoker84** [comment]
Thanks for the quick feedback. Per the post when I run service mongod status - I don't see Mongo running.

Maybe this is a stupid question, but I haven't personally setup a node server before. I'm assuming the related mongo directories/files within node_modules are the node js modules used to connect with MongoDB, correct?

So MongoDB would still have to be installed separately on the server, correct? If that is the case, are there are any specific config settings on MongoDB that are needed?

**Comment by Zach-Rose-Bose** [comment]
running `sudo npm install` as described in the instructions (which it sounds like you did saying the node_modules folder is there) should install everything. I'm pretty sure loopback contains everything necessary (including MongoDB itself). When I originally published this, I had validated that the steps in the README did work from scratch, without needing additional config...

With that said it's very possible that since this is over a year old and I have not maintained it at all, that things could be breaking because npm is installing newer versions that behave differently. Unfortunately I might not have time to dig into it further anytime soon.  :(

**Comment by DeMoehn** [comment]
Hello,

I was just on the go to install and test your scripts.

For the MongoDB problem, I had the same as MrJoker84.

You state that "I'm pretty sure loopback contains everything necessary (including MongoDB itself).".
Tbh. I don't think that you can easily install MongoDB just by "npm install".

After I've seen the MongoDB error, I checked if I have a MongoDB installation - which I did not.
I installed MongoDB on my own, after that, the MongoDB error was gone.

So maybe add that part?

**Comment by Zach-Rose-Bose** [comment]
Thanks @DeMoehn! When I wrote these instructions, it did work for me to just use the npm install, but that definitely may have changed in the meantime. I added a line to the README incorporating your feedback. If you have any suggestions for further details, let me know and/or feel free to submit a pull request!

**Comment by kr-maas** [comment]
A little late to the party - but I think I have a solution for @MrBobC: I ran into the same issue with discovery not working on a VirtualBox VM as my local server. 

After some digging (read: 2 hours of tinkering), found I could ping out to the local network but reaching back to the VM from the local network was throwing errors. I adjusted the settings on the VirtualBox console to put the VM on the same subnet as the rest of the devices and opened the firewall, worked right away.
